import type { ThemeId } from "@/lib/types"

// Biblioteca de catálogos prontos — produtos de exemplo com fotos reais,
// prontos para uso, agrupados por segmento de negócio. A lojista pode
// aplicar um catálogo inteiro ao cardápio (mantendo os produtos que já
// tem) e depois só trocar preços, nomes e fotos se quiser.

export interface PresetProduct {
  slug: string
  name: string
  description: string
  price: number
  image: string
  categoryName: string
  featured?: boolean
}

export interface PresetCatalog {
  id: ThemeId
  label: string
  description: string
  cover: string
  products: PresetProduct[]
}


export const PRESET_CATALOGS: Record<ThemeId, PresetCatalog> = {
  hamburgueria: {
    id: "hamburgueria",
    label: "Hamburgueria",
    description: "Smash burgers, combos e clássicos de lanchonete.",
    cover: "/images/presets/hamburgueria/cover.png",
    products: [
      {
        slug: "classico-bacon",
        name: "Clássico Bacon",
        description: "Pão brioche, smash burger, bacon crocante, cheddar e maionese da casa.",
        price: 24,
        image: "/images/presets/hamburgueria/classico-bacon.png",
        categoryName: "Hambúrgueres",
        featured: true,
      },
      {
        slug: "duplo-cheddar",
        name: "Duplo Cheddar",
        description: "Dois hambúrgueres suculentos, queijo cheddar duplo e molho especial.",
        price: 29,
        image: "/images/presets/hamburgueria/duplo-cheddar.png",
        categoryName: "Hambúrgueres",
      },
      {
        slug: "chicken-crispy",
        name: "Chicken Crispy",
        description: "Filé de frango empanado crocante, alface e maionese temperada.",
        price: 26,
        image: "/images/presets/hamburgueria/chicken-crispy.png",
        categoryName: "Hambúrgueres",
      },
      {
        slug: "smash-simples",
        name: "Smash Simples",
        description: "Smash burger suculento, queijo derretido e picles no pão brioche.",
        price: 18,
        image: "/images/presets/hamburgueria/smash-simples.jpg",
        categoryName: "Hambúrgueres",
      },
      {
        slug: "veggie-grelhado",
        name: "Veggie Grelhado",
        description: "Hambúrguer de grão-de-bico grelhado, rúcula e maionese vegana.",
        price: 25,
        image: "/images/presets/hamburgueria/veggie-grelhado.jpg",
        categoryName: "Hambúrgueres",
      },
      {
        slug: "barbecue-onion",
        name: "Barbecue Onion",
        description: "Burger ao molho barbecue, cebola crocante e cheddar.",
        price: 27,
        image: "/images/presets/hamburgueria/barbecue-onion.jpg",
        categoryName: "Hambúrgueres",
      },
      {
        slug: "combo-classico",
        name: "Combo Clássico",
        description: "Clássico Bacon + batata frita média + refrigerante lata.",
        price: 38,
        image: "/images/presets/hamburgueria/combo-classico.jpg",
        categoryName: "Combos",
      },
      {
        slug: "combo-duplo",
        name: "Combo Duplo Cheddar",
        description: "Duplo Cheddar + batata frita média + refrigerante lata.",
        price: 42,
        image: "/images/presets/hamburgueria/combo-duplo.jpg",
        categoryName: "Combos",
      },
      {
        slug: "combo-chicken",
        name: "Combo Chicken Crispy",
        description: "Chicken Crispy + batata frita média + refrigerante lata.",
        price: 40,
        image: "/images/presets/hamburgueria/combo-chicken.jpg",
        categoryName: "Combos",
      },
      {
        slug: "batata-frita",
        name: "Batata Frita",
        description: "Porção generosa de batata frita crocante, sal na medida.",
        price: 15,
        image: "/images/presets/hamburgueria/batata-frita.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "onion-rings",
        name: "Onion Rings",
        description: "Anéis de cebola empanados e fritos até ficarem crocantes.",
        price: 16,
        image: "/images/presets/hamburgueria/onion-rings.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "nuggets-frango",
        name: "Nuggets de Frango",
        description: "8 unidades crocantes, acompanha molho barbecue ou maionese.",
        price: 17,
        image: "/images/presets/hamburgueria/nuggets-frango.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "refrigerante-lata",
        name: "Refrigerante Lata",
        description: "Lata 350ml bem gelada.",
        price: 7,
        image: "/images/presets/hamburgueria/refrigerante-lata.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "suco-natural",
        name: "Suco Natural",
        description: "Copo 500ml, feito na hora com frutas selecionadas.",
        price: 10,
        image: "/images/presets/hamburgueria/suco-natural.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "milkshake-chocolate",
        name: "Milkshake de Chocolate",
        description: "Cremoso, feito com sorvete artesanal e calda de chocolate.",
        price: 16,
        image: "/images/presets/hamburgueria/milkshake-chocolate.jpg",
        categoryName: "Bebidas",
      },
    ],
  },
  espetaria: {
    id: "espetaria",
    label: "Espetaria",
    description: "Espetos grelhados na brasa, prontos para o rodízio ou delivery.",
    cover: "/images/presets/espetaria/cover.png",
    products: [
      {
        slug: "espeto-picanha",
        name: "Espeto de Picanha",
        description: "Picanha grelhada na brasa, temperada com sal grosso.",
        price: 14,
        image: "/images/presets/espetaria/espeto-picanha.png",
        categoryName: "Espetos",
        featured: true,
      },
      {
        slug: "espeto-frango-bacon",
        name: "Espeto de Frango com Bacon",
        description: "Frango enrolado no bacon, grelhado no ponto certo.",
        price: 12,
        image: "/images/presets/espetaria/espeto-frango-bacon.png",
        categoryName: "Espetos",
      },
      {
        slug: "espeto-coracao",
        name: "Espeto de Coração",
        description: "Coração de galinha grelhado, tempero especial da casa.",
        price: 10,
        image: "/images/presets/espetaria/espeto-coracao.png",
        categoryName: "Espetos",
      },
      {
        slug: "espeto-linguica",
        name: "Espeto de Linguiça",
        description: "Linguiça toscana grelhada na brasa, suculenta por dentro.",
        price: 11,
        image: "/images/presets/espetaria/espeto-linguica.jpg",
        categoryName: "Espetos",
      },
      {
        slug: "espeto-queijo-coalho",
        name: "Espeto de Queijo Coalho",
        description: "Queijo coalho grelhado, levemente dourado, com toque de orégano.",
        price: 12,
        image: "/images/presets/espetaria/espeto-queijo-coalho.jpg",
        categoryName: "Espetos",
      },
      {
        slug: "espeto-kafta",
        name: "Espeto de Kafta",
        description: "Kafta temperada com especiarias árabes, grelhada na brasa.",
        price: 13,
        image: "/images/presets/espetaria/espeto-kafta.jpg",
        categoryName: "Espetos",
      },
      {
        slug: "espeto-file-bacon",
        name: "Espeto de Filé com Bacon",
        description: "Filé mignon em cubos enrolado no bacon, grelhado ao ponto.",
        price: 16,
        image: "/images/presets/espetaria/espeto-file-bacon.jpg",
        categoryName: "Espetos",
      },
      {
        slug: "farofa-especial",
        name: "Farofa Especial",
        description: "Farofa crocante com bacon e cebola caramelizada.",
        price: 9,
        image: "/images/presets/espetaria/farofa-especial.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "vinagrete",
        name: "Vinagrete",
        description: "Tomate, cebola e pimentão picados, temperados na hora.",
        price: 6,
        image: "/images/presets/espetaria/vinagrete.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "pao-de-alho",
        name: "Pão de Alho",
        description: "Porção com 4 unidades, gratinado na brasa.",
        price: 12,
        image: "/images/presets/espetaria/pao-de-alho.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "arroz-branco",
        name: "Arroz Branco",
        description: "Porção individual, soltinho.",
        price: 8,
        image: "/images/presets/espetaria/arroz-branco.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "refrigerante-lata",
        name: "Refrigerante Lata",
        description: "Lata 350ml bem gelada.",
        price: 7,
        image: "/images/presets/espetaria/refrigerante-lata.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "suco-natural",
        name: "Suco Natural",
        description: "Copo 500ml, feito na hora com frutas selecionadas.",
        price: 10,
        image: "/images/presets/espetaria/suco-natural.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "agua-mineral",
        name: "Água Mineral",
        description: "Garrafa 500ml, com ou sem gás.",
        price: 5,
        image: "/images/presets/espetaria/agua-mineral.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "cerveja-long-neck",
        name: "Cerveja Long Neck",
        description: "Bem gelada, 355ml.",
        price: 9,
        image: "/images/presets/espetaria/cerveja-long-neck.jpg",
        categoryName: "Bebidas",
      },
    ],
  },
  pizzaria: {
    id: "pizzaria",
    label: "Pizzaria",
    description: "Pizzas de massa fina, sabores clássicos com foto profissional.",
    cover: "/images/presets/pizzaria/cover.png",
    products: [
      {
        slug: "pizza-margherita",
        name: "Pizza Margherita",
        description: "Molho de tomate, muçarela fresca, manjericão e azeite.",
        price: 42,
        image: "/images/presets/pizzaria/pizza-margherita.png",
        categoryName: "Pizzas",
        featured: true,
      },
      {
        slug: "pizza-calabresa",
        name: "Pizza Calabresa",
        description: "Calabresa fatiada, cebola e muçarela.",
        price: 45,
        image: "/images/presets/pizzaria/pizza-calabresa.png",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-quatro-queijos",
        name: "Pizza Quatro Queijos",
        description: "Muçarela, provolone, parmesão e gorgonzola.",
        price: 48,
        image: "/images/presets/pizzaria/pizza-quatro-queijos.png",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-portuguesa",
        name: "Pizza Portuguesa",
        description: "Presunto, ovos, cebola, azeitona e muçarela.",
        price: 46,
        image: "/images/presets/pizzaria/pizza-portuguesa.jpg",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-frango-catupiry",
        name: "Pizza Frango com Catupiry",
        description: "Frango desfiado temperado com catupiry cremoso.",
        price: 47,
        image: "/images/presets/pizzaria/pizza-frango-catupiry.jpg",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-pepperoni",
        name: "Pizza Pepperoni",
        description: "Fatias generosas de pepperoni e muçarela derretida.",
        price: 49,
        image: "/images/presets/pizzaria/pizza-pepperoni.jpg",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-napolitana",
        name: "Pizza Napolitana",
        description: "Tomate fatiado, muçarela, parmesão e orégano.",
        price: 44,
        image: "/images/presets/pizzaria/pizza-napolitana.jpg",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-vegetariana",
        name: "Pizza Vegetariana",
        description: "Brócolis, milho, tomate seco, pimentão e muçarela.",
        price: 45,
        image: "/images/presets/pizzaria/pizza-vegetariana.jpg",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-bacon-cheddar",
        name: "Pizza Bacon com Cheddar",
        description: "Bacon crocante e cheddar cremoso sobre muçarela.",
        price: 48,
        image: "/images/presets/pizzaria/pizza-bacon-cheddar.jpg",
        categoryName: "Pizzas",
      },
      {
        slug: "pizza-chocolate-morango",
        name: "Pizza de Chocolate com Morango",
        description: "Chocolate ao leite derretido e morangos fatiados.",
        price: 38,
        image: "/images/presets/pizzaria/pizza-chocolate-morango.jpg",
        categoryName: "Pizzas Doces",
      },
      {
        slug: "pizza-banana-canela",
        name: "Pizza de Banana com Canela",
        description: "Banana caramelizada, canela e leite condensado.",
        price: 36,
        image: "/images/presets/pizzaria/pizza-banana-canela.jpg",
        categoryName: "Pizzas Doces",
      },
      {
        slug: "pizza-doce-de-leite-coco",
        name: "Pizza Doce de Leite com Coco",
        description: "Doce de leite cremoso com coco ralado tostado.",
        price: 37,
        image: "/images/presets/pizzaria/pizza-doce-de-leite-coco.jpg",
        categoryName: "Pizzas Doces",
      },
      {
        slug: "refrigerante-2l",
        name: "Refrigerante 2L",
        description: "Garrafa 2 litros, sabores variados.",
        price: 14,
        image: "/images/presets/pizzaria/refrigerante-2l.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "suco-natural",
        name: "Suco Natural",
        description: "Copo 500ml, feito na hora com frutas selecionadas.",
        price: 10,
        image: "/images/presets/pizzaria/suco-natural.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "agua-mineral",
        name: "Água Mineral",
        description: "Garrafa 500ml, com ou sem gás.",
        price: 5,
        image: "/images/presets/pizzaria/agua-mineral.jpg",
        categoryName: "Bebidas",
      },
    ],
  },
  acai: {
    id: "acai",
    label: "Açaí",
    description: "Bowls de açaí prontos, com combinações que mais vendem.",
    cover: "/images/presets/acai/cover.png",
    products: [
      {
        slug: "acai-tradicional",
        name: "Açaí Tradicional",
        description: "Açaí puro com granola crocante e banana fatiada.",
        price: 18,
        image: "/images/presets/acai/acai-tradicional.png",
        categoryName: "Açaí",
        featured: true,
      },
      {
        slug: "acai-morango-ninho",
        name: "Açaí com Morango e Leite Ninho",
        description: "Açaí cremoso, morangos frescos e leite em pó.",
        price: 22,
        image: "/images/presets/acai/acai-morango-ninho.png",
        categoryName: "Açaí",
      },
      {
        slug: "acai-fit",
        name: "Açaí Fit",
        description: "Açaí com granola, morango e paçoca, sem adição de açúcar.",
        price: 20,
        image: "/images/presets/acai/acai-fit.png",
        categoryName: "Açaí",
      },
      {
        slug: "acai-nutella",
        name: "Açaí com Nutella",
        description: "Açaí cremoso com generosa camada de Nutella.",
        price: 24,
        image: "/images/presets/acai/acai-nutella.jpg",
        categoryName: "Açaí",
      },
      {
        slug: "acai-kit-kat",
        name: "Açaí com Kit Kat",
        description: "Açaí batido com pedaços de Kit Kat.",
        price: 25,
        image: "/images/presets/acai/acai-kit-kat.jpg",
        categoryName: "Açaí",
      },
      {
        slug: "acai-300ml",
        name: "Açaí 300ml",
        description: "Copo tradicional, monte com seus acompanhamentos favoritos.",
        price: 15,
        image: "/images/presets/acai/acai-300ml.jpg",
        categoryName: "Açaí",
      },
      {
        slug: "acai-500ml",
        name: "Açaí 500ml",
        description: "Copo grande, ideal para dividir.",
        price: 23,
        image: "/images/presets/acai/acai-500ml.jpg",
        categoryName: "Açaí",
      },
      {
        slug: "acai-pacoca",
        name: "Açaí com Paçoca",
        description: "Açaí cremoso coberto com paçoca triturada.",
        price: 21,
        image: "/images/presets/acai/acai-pacoca.jpg",
        categoryName: "Açaí",
      },
      {
        slug: "granola-extra",
        name: "Granola Extra",
        description: "Porção adicional de granola crocante.",
        price: 4,
        image: "/images/presets/acai/granola-extra.jpg",
        categoryName: "Complementos",
      },
      {
        slug: "leite-condensado",
        name: "Leite Condensado",
        description: "Porção adicional de leite condensado.",
        price: 3,
        image: "/images/presets/acai/leite-condensado.jpg",
        categoryName: "Complementos",
      },
      {
        slug: "morango-extra",
        name: "Morango Extra",
        description: "Porção adicional de morangos frescos fatiados.",
        price: 5,
        image: "/images/presets/acai/morango-extra.jpg",
        categoryName: "Complementos",
      },
      {
        slug: "castanha-fatias",
        name: "Castanha em Fatias",
        description: "Porção adicional de castanha-do-pará fatiada.",
        price: 5,
        image: "/images/presets/acai/castanha-fatias.jpg",
        categoryName: "Complementos",
      },
      {
        slug: "agua-de-coco",
        name: "Água de Coco",
        description: "Copo 300ml, gelada.",
        price: 8,
        image: "/images/presets/acai/agua-de-coco.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "suco-natural",
        name: "Suco Natural",
        description: "Copo 500ml, feito na hora com frutas selecionadas.",
        price: 10,
        image: "/images/presets/acai/suco-natural.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "refrigerante-lata",
        name: "Refrigerante Lata",
        description: "Lata 350ml bem gelada.",
        price: 7,
        image: "/images/presets/acai/refrigerante-lata.jpg",
        categoryName: "Bebidas",
      },
    ],
  },
  confeitaria: {
    id: "confeitaria",
    label: "Confeitaria",
    description: "Bolos, doces e tortas com fotos de vitrine de confeitaria.",
    cover: "/images/presets/confeitaria/cover.png",
    products: [
      {
        slug: "bolo-chocolate",
        name: "Bolo de Chocolate com Ganache",
        description: "Fatia generosa, massa fofinha e ganache cremoso.",
        price: 14,
        image: "/images/presets/confeitaria/bolo-chocolate.png",
        categoryName: "Doces",
        featured: true,
      },
      {
        slug: "brigadeiro-gourmet",
        name: "Brigadeiro Gourmet",
        description: "Caixa com 6 unidades, cobertura de chocolate belga.",
        price: 18,
        image: "/images/presets/confeitaria/brigadeiro-gourmet.png",
        categoryName: "Doces",
      },
      {
        slug: "torta-morango",
        name: "Torta de Morango",
        description: "Base crocante, creme de confeiteiro e morangos frescos.",
        price: 16,
        image: "/images/presets/confeitaria/torta-morango.png",
        categoryName: "Doces",
      },
      {
        slug: "bolo-red-velvet",
        name: "Bolo Red Velvet",
        description: "Massa aveludada com cobertura de cream cheese.",
        price: 16,
        image: "/images/presets/confeitaria/bolo-red-velvet.jpg",
        categoryName: "Doces",
      },
      {
        slug: "cheesecake-frutas-vermelhas",
        name: "Cheesecake de Frutas Vermelhas",
        description: "Base amanteigada, recheio cremoso e calda de frutas vermelhas.",
        price: 17,
        image: "/images/presets/confeitaria/cheesecake-frutas-vermelhas.jpg",
        categoryName: "Doces",
      },
      {
        slug: "palha-italiana",
        name: "Palha Italiana",
        description: "Caixa com 6 unidades, chocolate cremoso e biscoito crocante.",
        price: 16,
        image: "/images/presets/confeitaria/palha-italiana.jpg",
        categoryName: "Doces",
      },
      {
        slug: "bem-casado",
        name: "Bem-Casado",
        description: "Caixa com 6 unidades, recheio de doce de leite.",
        price: 15,
        image: "/images/presets/confeitaria/bem-casado.jpg",
        categoryName: "Doces",
      },
      {
        slug: "cupcake-recheado",
        name: "Cupcake Recheado",
        description: "Unidade com recheio surpresa e cobertura de buttercream.",
        price: 9,
        image: "/images/presets/confeitaria/cupcake-recheado.jpg",
        categoryName: "Doces",
      },
      {
        slug: "torta-limao",
        name: "Torta de Limão",
        description: "Base crocante, creme de limão e merengue maçaricado.",
        price: 16,
        image: "/images/presets/confeitaria/torta-limao.jpg",
        categoryName: "Doces",
      },
      {
        slug: "coxinha-gourmet",
        name: "Coxinha Gourmet",
        description: "Recheio cremoso de frango com catupiry, empanada na hora.",
        price: 8,
        image: "/images/presets/confeitaria/coxinha-gourmet.jpg",
        categoryName: "Salgados",
      },
      {
        slug: "empada-de-frango",
        name: "Empada de Frango",
        description: "Massa amanteigada com recheio cremoso de frango.",
        price: 8,
        image: "/images/presets/confeitaria/empada-de-frango.jpg",
        categoryName: "Salgados",
      },
      {
        slug: "quiche-alho-poro",
        name: "Quiche de Alho-Poró",
        description: "Fatia individual, massa crocante e recheio cremoso.",
        price: 12,
        image: "/images/presets/confeitaria/quiche-alho-poro.jpg",
        categoryName: "Salgados",
      },
      {
        slug: "cafe-expresso",
        name: "Café Expresso",
        description: "Dose curta, torra especial da casa.",
        price: 6,
        image: "/images/presets/confeitaria/cafe-expresso.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "suco-natural",
        name: "Suco Natural",
        description: "Copo 500ml, feito na hora com frutas selecionadas.",
        price: 10,
        image: "/images/presets/confeitaria/suco-natural.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "agua-mineral",
        name: "Água Mineral",
        description: "Garrafa 500ml, com ou sem gás.",
        price: 5,
        image: "/images/presets/confeitaria/agua-mineral.jpg",
        categoryName: "Bebidas",
      },
    ],
  },
  natural: {
    id: "natural",
    label: "Natural",
    description: "Saladas, sucos e bowls saudáveis para cardápio fit.",
    cover: "/images/presets/natural/cover.png",
    products: [
      {
        slug: "salada-caesar",
        name: "Salada Caesar com Frango",
        description: "Alface fresca, frango grelhado, croutons e parmesão.",
        price: 26,
        image: "/images/presets/natural/salada-caesar.png",
        categoryName: "Pratos Naturais",
        featured: true,
      },
      {
        slug: "suco-detox",
        name: "Suco Detox Verde",
        description: "Couve, limão, gengibre e maçã verde.",
        price: 12,
        image: "/images/presets/natural/suco-detox.png",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "bowl-quinoa",
        name: "Bowl de Quinoa com Legumes",
        description: "Quinoa, legumes grelhados e molho de iogurte.",
        price: 28,
        image: "/images/presets/natural/bowl-quinoa.png",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "bowl-frango-grelhado",
        name: "Bowl de Frango Grelhado",
        description: "Frango grelhado, arroz integral, legumes e molho especial.",
        price: 27,
        image: "/images/presets/natural/bowl-frango-grelhado.jpg",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "salada-grao-de-bico",
        name: "Salada de Grão-de-Bico",
        description: "Grão-de-bico, tomate, pepino e molho de limão.",
        price: 22,
        image: "/images/presets/natural/salada-grao-de-bico.jpg",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "wrap-integral-frango",
        name: "Wrap Integral de Frango",
        description: "Tortilha integral, frango grelhado, alface e molho leve.",
        price: 24,
        image: "/images/presets/natural/wrap-integral-frango.jpg",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "omelete-fit",
        name: "Omelete Fit",
        description: "Claras de ovo, espinafre e queijo cottage.",
        price: 20,
        image: "/images/presets/natural/omelete-fit.jpg",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "salmao-grelhado-legumes",
        name: "Salmão Grelhado com Legumes",
        description: "Filé de salmão grelhado, legumes salteados no azeite.",
        price: 38,
        image: "/images/presets/natural/salmao-grelhado-legumes.jpg",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "salada-caprese",
        name: "Salada Caprese",
        description: "Tomate, muçarela de búfala, manjericão e azeite.",
        price: 23,
        image: "/images/presets/natural/salada-caprese.jpg",
        categoryName: "Pratos Naturais",
      },
      {
        slug: "mix-castanhas",
        name: "Mix de Castanhas",
        description: "Porção individual, castanhas e nozes selecionadas.",
        price: 10,
        image: "/images/presets/natural/mix-castanhas.jpg",
        categoryName: "Complementos",
      },
      {
        slug: "pao-integral",
        name: "Pão Integral",
        description: "Fatia dupla, cereais e sementes.",
        price: 6,
        image: "/images/presets/natural/pao-integral.jpg",
        categoryName: "Complementos",
      },
      {
        slug: "molho-de-iogurte",
        name: "Molho de Iogurte",
        description: "Porção adicional, iogurte natural com ervas.",
        price: 4,
        image: "/images/presets/natural/molho-de-iogurte.jpg",
        categoryName: "Complementos",
      },
      {
        slug: "agua-de-coco",
        name: "Água de Coco",
        description: "Copo 300ml, gelada.",
        price: 8,
        image: "/images/presets/natural/agua-de-coco.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "suco-frutas-vermelhas",
        name: "Suco Natural de Frutas Vermelhas",
        description: "Copo 500ml, feito na hora, sem açúcar.",
        price: 12,
        image: "/images/presets/natural/suco-frutas-vermelhas.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "cha-gelado-natural",
        name: "Chá Gelado Natural",
        description: "Copo 500ml, chá de frutas com hortelã.",
        price: 10,
        image: "/images/presets/natural/cha-gelado-natural.jpg",
        categoryName: "Bebidas",
      },
    ],
  },
  premium: {
    id: "premium",
    label: "Casa de Carnes",
    description: "Cortes nobres e pratos de churrascaria para cardápio premium.",
    cover: "/images/presets/premium/cover.png",
    products: [
      {
        slug: "picanha-chapa",
        name: "Picanha na Chapa",
        description: "Picanha grelhada ao ponto, acompanhada de farofa e vinagrete.",
        price: 68,
        image: "/images/presets/premium/picanha-chapa.png",
        categoryName: "Cortes Nobres",
        featured: true,
      },
      {
        slug: "costela-assada",
        name: "Costela Assada 12h",
        description: "Costela lenta, desmanchando, com molho barbecue da casa.",
        price: 72,
        image: "/images/presets/premium/costela-assada.png",
        categoryName: "Cortes Nobres",
      },
      {
        slug: "file-mignon-madeira",
        name: "Filé Mignon ao Molho Madeira",
        description: "Filé mignon grelhado com molho madeira e purê.",
        price: 64,
        image: "/images/presets/premium/file-mignon-madeira.png",
        categoryName: "Cortes Nobres",
      },
      {
        slug: "ancho-na-brasa",
        name: "Ancho na Brasa",
        description: "Corte ancho grelhado na brasa, suculento e macio.",
        price: 74,
        image: "/images/presets/premium/ancho-na-brasa.jpg",
        categoryName: "Cortes Nobres",
      },
      {
        slug: "fraldinha-grelhada",
        name: "Fraldinha Grelhada",
        description: "Fraldinha grelhada ao ponto, temperada com sal grosso.",
        price: 58,
        image: "/images/presets/premium/fraldinha-grelhada.jpg",
        categoryName: "Cortes Nobres",
      },
      {
        slug: "maminha-ao-alho",
        name: "Maminha ao Alho",
        description: "Maminha grelhada com lâminas de alho tostado.",
        price: 56,
        image: "/images/presets/premium/maminha-ao-alho.jpg",
        categoryName: "Cortes Nobres",
      },
      {
        slug: "cupim-desfiado",
        name: "Cupim Desfiado",
        description: "Cupim assado lentamente e desfiado à mão.",
        price: 62,
        image: "/images/presets/premium/cupim-desfiado.jpg",
        categoryName: "Cortes Nobres",
      },
      {
        slug: "farofa-da-casa",
        name: "Farofa da Casa",
        description: "Farofa crocante com bacon e cebola caramelizada.",
        price: 12,
        image: "/images/presets/premium/farofa-da-casa.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "vinagrete",
        name: "Vinagrete",
        description: "Tomate, cebola e pimentão picados, temperados na hora.",
        price: 8,
        image: "/images/presets/premium/vinagrete.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "arroz-branco",
        name: "Arroz Branco",
        description: "Porção individual, soltinho.",
        price: 10,
        image: "/images/presets/premium/arroz-branco.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "pure-de-batata",
        name: "Purê de Batata",
        description: "Cremoso, feito com manteiga e leite.",
        price: 14,
        image: "/images/presets/premium/pure-de-batata.jpg",
        categoryName: "Acompanhamentos",
      },
      {
        slug: "vinho-tinto-taca",
        name: "Vinho Tinto Taça",
        description: "Seleção da casa, servido em taça.",
        price: 22,
        image: "/images/presets/premium/vinho-tinto-taca.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "refrigerante-lata",
        name: "Refrigerante Lata",
        description: "Lata 350ml bem gelada.",
        price: 8,
        image: "/images/presets/premium/refrigerante-lata.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "suco-natural",
        name: "Suco Natural",
        description: "Copo 500ml, feito na hora com frutas selecionadas.",
        price: 12,
        image: "/images/presets/premium/suco-natural.jpg",
        categoryName: "Bebidas",
      },
      {
        slug: "agua-com-gas",
        name: "Água com Gás",
        description: "Garrafa 500ml, bem gelada.",
        price: 7,
        image: "/images/presets/premium/agua-com-gas.jpg",
        categoryName: "Bebidas",
      },
    ],
  },
}

export const PRESET_CATALOG_ORDER: ThemeId[] = [
  "hamburgueria",
  "espetaria",
  "pizzaria",
  "acai",
  "confeitaria",
  "natural",
  "premium",
]
